name: PR Use Cases Validation

on:
   pull_request:
     types:
      # Configure these types yourself!
      - opened
      - edited
      - reopened
      - synchronize

   workflow_dispatch:

jobs:
  pr_usecases_validation:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate PR Use Cases
      uses: nivisi/dart_pull_request_use_case_validator@0.0.3
      with:
         # GitHub Access Token
         # Required. Default is ${{ github.token }}
         github-token: ${{ github.token }}

         # Desired public callable method of a use case.
         # Required. Default is Â«runÂ»
         method-name: run

         # The message that is printed in the approve review message.
         # Optional. Default is Â«The use cases for this pull requests were implemented correctly! Good job ğŸ‘Â»
         approve-message: Great job

         # Whether a use case file must contain only one class.
         # Required. Default is Â«trueÂ»
         single-class-in-file: true
